### ISSUE TITLE
Ignoring hidden files on MacOS

### ISSUE THREAD

**Issue by rsmything** [SecretVault-elixir/secret_vault#3]
If some hidden files exist in prefix folders it tries to apply them as variables and crashes
Especially such files as .keep and .DS-Store.

<img width="737" alt="Снимок экрана 2023-07-06 в 10 31 57" src="https://github.com/SecretVault-elixir/secret_vault/assets/11719983/c2685ae6-4b05-4c1d-8cf6-47343c1b14ba">

<img width="735" alt="Снимок экрана 2023-07-06 в 10 32 20" src="https://github.com/SecretVault-elixir/secret_vault/assets/11719983/dc227443-7607-466c-9a73-46eb1cbc6937">

**Comment by hissssst** [comment]
How do you use the library?

**Comment by hissssst** [comment]
Fixed in 1.2.1
